SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;


SELECT INF.CODIGO_DO_PRODUTO, TDP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE_PRODUTOS
FROM ITENS_NOTAS_FISCAIS INF INNER JOIN TABELA_DE_PRODUTOS TDP ON TDP.CODIGO_DO_PRODUTO=INF.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TDP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT COUNT (*) FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT TV.NOME AS NOME_VENDEDOR, TV.BAIRRO, TC.NOME AS NOME_CLIENTE, TC.VOLUME_DE_COMPRA
AS  VALOR_COMPRADO_PELO_CLINTE
FROM TABELA_DE_VENDEDORES TV INNER JOIN TABELA_DE_CLIENTES TC 
ON TV.BAIRRO=TC.BAIRRO WHERE TV.NOME = 'CLAUDIA MORAIS'
ORDER BY TC.VOLUME_DE_COMPRA ;


SELECT DISTINCT NOME FROM TABELA_DE_VENDEDORES;