/*SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;*/

/*SELECT INF.CODIGO_DO_PRODUTO, TDP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE_PRODUTOS
FROM ITENS_NOTAS_FISCAIS INF INNER JOIN TABELA_DE_PRODUTOS TDP ON TDP.CODIGO_DO_PRODUTO=INF.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TDP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;*/

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM [SUCOS_FRUTAS].[dbo].[ITENS_NOTAS_FISCAIS]  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;
